name: "TsunamiSight sighting client"

services:
  tsunamisight-client:
    image: vuln_lookup_tsunamisight-client
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_IMAGE=python:3.11-slim
    restart: always
    environment:
      - PYTHONUNBUFFERED=TRUE
      - TSUNAMISIGHT_CONFIG=/etc/conf.py
    volumes:
      - "./tsunamisight/conf.py:/etc/conf.py"
